//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildingOrganizationNazarov.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamEmployee
    {
        public int ID { get; set; }
        public int IDTeam { get; set; }
        public int IDEmployee { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Team Team { get; set; }
    }
}
